server:
  port: 8091

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

---

spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: stock-decrease-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            json:
              default:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9000/~/joyMall;
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


---

spring:
  config:
    activate:
      on-profile: prod

  kafka:
    bootstrap-servers: 192.168.0.9:9092
    consumer:
      group-id: stock-decrease-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: o`rg.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            json:
              default:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JOY_MALL_DB_URL}
    username: ${JOY_MALL_DB_USER}
    password: ${JOY_MALL_DB_PASSWORD}

  data:
    redis:
      host: ${JOY_MALL_REDIS_URL}
      port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE